# Generated by Django 5.1 on 2024-10-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_groups_customuser_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image_url',
            field=models.URLField(blank=True, default='/assets/img/profile_pic_anon.svg'),
        ),
    ]
