# Generated by Django 5.1 on 2024-10-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image_url',
            field=models.URLField(default='http://localhost:4200/assets/img/profile_pic_anon.svg'),
        ),
    ]
